# Site settings
title: Ciao
email: info@haptrix.com
description: "Ciao App is a minimal meetup.com client. The feed contains just the information you need and no clutter."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Malolan Santhanakrishnan
  location: Waltham, MA
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:

# Postal address (add as many lines as necessary)
address:
  - line: Waltham, MA

# Credits content
credits: 'This site runs on GitHub Pages.'

# Build settings
markdown: kramdown
permalink: pretty
